### ISSUE TITLE
Some tests fail on OSX 10.11 with latest Cuda 8, SBCL 1.3.1 x64

### ISSUE THREAD

**Issue by atomontage** [melisgl/mgl-mat#3]
test-asum and test-nrm2

* testing MGL-MAT:ASUM
** ctype: :FLOAT
*** cuda enabled: NIL
**** foreign array strategy: :PINNED

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1002ACCAD3}>:
  The assertion
  (MGL-MAT::~= (MGL-MAT:COERCE-TO-CTYPE 3) (MGL-MAT:ASUM MGL-MAT::X)) failed
  with (MGL-MAT:COERCE-TO-CTYPE 3) = 3.0, (MGL-MAT:ASUM MGL-MAT::X) = 0.0.

* testing MGL-MAT:NRM2
** ctype: :FLOAT
*** cuda enabled: NIL
**** foreign array strategy: :PINNED

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {1002ACCAD3}>:
  The assertion
  (MGL-MAT::~= (SQRT (MGL-MAT:COERCE-TO-CTYPE 3)) (MGL-MAT:NRM2 MGL-MAT::X))
  failed with (SQRT (MGL-MAT:COERCE-TO-CTYPE 3)) = 1.7320508,
  (MGL-MAT:NRM2 MGL-MAT::X) = -3.689349e19.

**Comment by melisgl** [comment]
I missed this issue totally a couple of years ago. Now there is a similar report in https://github.com/melisgl/mgl/issues/8.
