### ISSUE TITLE
copy-column throws failed assertion on ccl

### ISSUE THREAD

**Issue by jccerrillo** [melisgl/mgl-mat#4]
I get a failed assertion on ccl : 

NN> (make-mat '(3 3) :initial-element 0d0)
#<MAT 3x3 - #x3020040C781D>
NN> (copy-row * 2)
#<MAT 3 F #x3020040C8BFD>
NN> (make-mat '(3 3) :initial-element 0d0)
#<MAT 3x3 - #x3020040C701D>
NN> (copy-column * 1)

Failed assertion: (<= (ABS (* MGL-MAT::N MGL-MAT::INCX))
                      (MAT-SIZE MGL-MAT::X))

Am I doing something wrong?

best,

jc

**Comment by melisgl** [comment]
At the risk of being a bit late to answer (ouch), it's because COPY-COLUMN wants a 2d matrix. On SBCL I get a slightly more informative error from COPY-COLUMN:

    Error while parsing arguments to DESTRUCTURING-BIND:
      too few elements in
        (3)
      to satisfy lambda list
        (N-ROWS N-COLUMNS):
      exactly 2 expected, but got 1
